"use client"
import Script from 'next/script'
import { AuthProvider } from '@/context/AuthContext'
import { ProductProvider } from '@/context/ProductContext'
import { CategoryProvider } from '@/context/CategoryContext'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'


import Sidebar from '@/components/LayoutComponents/Sidebar'
const inter = Inter({ subsets: ['latin'] })


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <Script
        src="https://upload-widget.cloudinary.com/global/all.js"
        onLoad={() => {
          console.log('Script has loaded')
        }}
      />
      <body className={inter.className}>
        <AuthProvider>
          <CategoryProvider>
            <ProductProvider>
              {children}
            </ProductProvider>
          </CategoryProvider>
        </AuthProvider>
      </body>
    </html>
  )
}